DROP SCHEMA IF EXISTS IFCD0111;
CREATE SCHEMA IF NOT EXISTS IFCD0111;
USE IFCD0111;
CREATE TABLE ALUMNO(
    NOMBRE varchar(25),
    DNI char(9) PRIMARY KEY,
    EMAIL VARCHAR(50),
    FECHA_NACIMIENTO DATE
);
CREATE TABLE MODULO_CERTIFICADO (
    TIPO VARCHAR(50),
    CODIGO_MOD_CERT int auto_increment,
    NOMBRE VARCHAR(100),
    PRIMARY KEY(CODIGO_MOD_CERT)
);

CREATE TABLE MODULO_FORMATIVO (
	CODIGO_MOD_CERT int,
    CODIGO_MF CHAR(7) , 
    PRIMARY KEY(CODIGO_MOD_CERT,CODIGO_MF),
    CONSTRAINT FOREIGN KEY MF_MOD_CERT (CODIGO_MOD_CERT) REFERENCES MODULO_CERTIFICADO (CODIGO_MOD_CERT) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE MODULO_PRACTICA (
    CODIGO_MOD_CERT int,
    CODIGO_MP CHAR(6)  ,
    HORAS INT, 
    PRIMARY KEY(CODIGO_MOD_CERT,CODIGO_MP),
    CONSTRAINT FOREIGN KEY MP_MOD_CERT (CODIGO_MOD_CERT) REFERENCES MODULO_CERTIFICADO (CODIGO_MOD_CERT) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE UNIDAD_FORMATIVA(
    CODIGO_UF CHAR(6) PRIMARY KEY,
    CODIGO_MOD_CERT int,
    CODIGO_MF CHAR(7), 
    NOMBRE VARCHAR(100) NOT NULL,
    HORAS INT,
    CONSTRAINT FOREIGN KEY UF_MF_COD_MOD_CERT (CODIGO_MOD_CERT) REFERENCES MODULO_CERTIFICADO (CODIGO_MOD_CERT) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY UF_MF_COD_MF (CODIGO_MOD_CERT, CODIGO_MF) REFERENCES MODULO_FORMATIVO (CODIGO_MOD_CERT, CODIGO_MF) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE MATRICULA (
	DNI_MATRICULA CHAR(9),
    CODI_UF CHAR(6),
    CONSTRAINT FOREIGN KEY MATRICULA_ALUMN_DNI (DNI_MATRICULA) REFERENCES ALUMNO (DNI) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY MATRICULA_UF_CODI_UF (CODI_UF) REFERENCES UNIDAD_FORMATIVA (CODIGO_UF) ON DELETE RESTRICT ON UPDATE CASCADE
)